import type { Metadata } from 'next'
import { Toaster } from "@/components/ui/toaster"
import './globals.css'
import AuthProvider from '@/context/Auth.context'
import SocketProvider from '@/context/Socket.context'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body className={`flex w-full min-h-screen`}>
        <AuthProvider>
          <SocketProvider>
            {children}
          </SocketProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
